/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IDCardInfoManager */

#ifndef _Included_IDCardInfoManager
#define _Included_IDCardInfoManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IDCardInfoManager
 * Method:    CVR_InitComm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_IDCardInfoManager_CVR_1InitComm
  (JNIEnv *, jobject, jint);

/*
 * Class:     IDCardInfoManager
 * Method:    read
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_IDCardInfoManager_read
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     IDCardInfoManager
 * Method:    read_more
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_IDCardInfoManager_read_1more
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
